export const searchData = [
  {
    title: "To Bring",
    screen: "ToBring",
    keywords: [
      "packing",
      "clothes",
      "food",
      "grocery",
      "groceries",
      "supplies",
      "luggage",
    ],
    content: `
      Please bring warm clothes, walking shoes, groceries, personal items,
      chargers, and anything else you may need during your stay.
    `,
  },
    {
        title: "Navigation",
        screen: "HomeScreen",
        keywords: [
        "drive",
        "driving",
        "distance",
        "directions",
        "stops",
        "airport",
        "luggage",
        "map"
        ],
        content: `Navigate from your location to the The Keep or airport `,
    },
    {
        title: "Navigation",
        screen: "HomeScreen",
        keywords: [
        "arrival",
        "check in",
        "check-in",
        "self check-in",
        "access",
        "code",
        "code",
        "instructions",
        "entry",
        "enter",
        "entrance",
        "main entrance",
        "lockbox",
        "lock box",
        "key",
        "keys",
        "email",
        "received code",
        "before travel",
        "travel",
        "property",
        "address",
        "535 New England Road",
        "Goulds Country",
        "Tasmania",
        "Australia",
        "contact",
        "admin",
        "admin@thekeeptasmania.com.au",

        "check-in time",
        "check in time",
        "2pm",
        "2 pm",
        "14:00",
        "early arrival",
        "early check in",
        "early check-in",
        "arrive early",
        "arriving early",
        "local area",
        "things to do",
        "wait",
        "waiting",

        "parking",
        "free parking",
        "premises parking",
        "street parking",
        "vehicle",
        "car",
        "park",
        "designated parking",
        "parking area",

        "late arrival",
        "late arrivals",
        "arrive late",
        "arriving late",
        "late check in",
        "late check-in",
        "inform",
        "notify",
        "advance notice",
        "flexible check in",
        "flexible check-in",
        "smooth arrival",
        ],
        content: `Navigate from your location to the The Keep or airport `,
    },

];